name: AutoNexus
version: 1.0.0
main: lytblu7.autonexus.server.NexusServer
api-version: 1.20
commands:
  nexus:
    description: Main command
    usage: /nexus
permissions:
  autonexus.admin:
    description: Allows using /nexus admin commands
    default: op
  autonexus.command.join:
    description: Allows using /nexus join when require-permission is true
    default: false
